resolver: lts-3.4
packages:
  - serversession
  - serversession-backend-acid-state
  - serversession-backend-persistent
  - serversession-backend-redis
  - serversession-frontend-snap
  - serversession-frontend-wai
  - serversession-frontend-yesod
  - examples/serversession-example-yesod-persistent
extra-deps:
  - acid-state-0.14.0
  - nonce-1.0.2
  - wai-session-0.3.2
  - safecopy-0.9.0.1
  - cereal-0.5.1.0
